name: gemma3_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - cudatoolkit=11.8
  - pytorch=2.2.0
  - torchvision=0.17.0
  - numpy>=1.24.0
  - pip:
    - -r requirements.txt